services:
  app:
    build:
      context: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/inventorymanagement
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorymanagement
    ports:
      - "3308:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge